### ISSUE TITLE
Add bibcodes for CfA spectra

### ISSUE THREAD

**Issue by guillochon** [astrocatalogs/astrocats#18]
Currently the only source referenced for spectra that appear on the CfA's page is the URL to the page itself, however we do have the publication info available from that page. This should be added for completeness.

**Comment by jparrent** [comment]
Dropping these here for now.
CfA_Ia -- Blondin+12 -- http://adsabs.harvard.edu/abs/2012AJ....143..126B

Some of these (432 spectra) were published in Matheson+08 -- http://adsabs.harvard.edu/abs/2008AJ....135.1598M -- Some others were published in other works, although I would expect a number of those data sets to already be connected to the original source; could be wrong.

CfA_Ibc -- Modjaz+14 -- http://adsabs.harvard.edu/abs/2014AJ....147...99M

**Comment by jparrent** [comment]
Published CfA_Ia data includes:

SN 1998aq, Branch+03 -- http://adsabs.harvard.edu/abs/2003AJ....126.1489B
SN  1998bu, Jha+99b -- http://adsabs.harvard.edu/abs/1999ApJS..125...73J
SN  1999by,  Garnavich+04 -- http://adsabs.harvard.edu/abs/2004ApJ...613.1120G
SN  2001ay,  Krisciunas+11 -- http://adsabs.harvard.edu/abs/2011AJ....142...74K
SN  2001eh and SN 2001ep, Sauer+08 -- http://adsabs.harvard.edu/abs/2008MNRAS.391.1605S
SN 2002cx, Li+03 -- http://adsabs.harvard.edu/abs/2003PASP..115..453L
SN 2005cf, Wang+09b -- http://adsabs.harvard.edu/abs/2009ApJ...697..380W
SN 2006bt, Foley+10 -- http://adsabs.harvard.edu/abs/2010ApJ...708.1748F
SN 2006gz, Hicken+07 -- http://adsabs.harvard.edu/abs/2007ApJ...669L..17H

**Comment by guillochon** [comment]
The proper sources should be attached now to the CfA data, will close after checking on the catalog.

**Comment by guillochon** [comment]
This has now been done, closing.
