### ISSUE TITLE
[UCB] Error for one epoch of 90M spectrum

### ISSUE THREAD

**Issue by jparrent** [astrocatalogs/astrocats#25]
Thank you to Isaac Shivvers and Jeff Silverman for the clarification on this one. They found the same issue some time ago:

https://sne.space/sne/SN1990M/
The top-most spectrum is being posted with an epoch of -75, when it should instead be closer to +216 according to Silverman et al. (2012) -- 2012MNRAS.425.1789S

The affected file is:
sne-external-spectra/UCB/sn1990m-19900401-opt.flm

From the looks of it, it's definitely at day +200-300, and there's no such thing as -75 for a SN Ia. For 87A, yes. 

Given that there is a legitimate misprint in the date for this spectrum, and that 1991 would make sense instead of 1990 (private comm, IS, JS), I think it would be fine to change the year to 1991 in the filename. But we can discuss later before I go and change anything. At any rate, hello future SN enthusiasts, watch your step.

**Comment by guillochon** [comment]
This was fixed on the UCB end, closing.
