### ISSUE TITLE
[SuSpect] Add FITS header files to repository

### ISSUE THREAD

**Issue by jparrent** [astrocatalogs/astrocats#27]
Original poster, guillochon: I'd like to add the metadata from the SUSPECT spectra to the catalog, and I think the easiest way to do this is to just add all the FITS header files to the SUSPECT folder. That way I can parse the accompanying header file when I read in the spectra.

*migrated issue

**Comment by guillochon** [comment]
This issue was moved to astrocatalogs/supernovae#7
