### ISSUE TITLE
[Superfit] Redshift corrections, dupes, and epochs

### ISSUE THREAD

**Issue by jparrent** [astrocatalogs/astrocats#28]
I believe I'm coming to a consensus on the Superfit spectra. It's fine if and when they are shown, but:
--they appear to be rest frame spectra, so they need not be corrected for redshift in the import script. There may be exceptions, but for the most part this is true, and I'm tracking the exceptions.
--the epochs for some spectra appear to be the negative of what they should be, e.g., day -116 for 90aa I'm guessing should go to +116. This seems to be the case for others, and the underlying thing here is that there are a few naming conventions for the superfit files. Anything with a "m05" in the filename refers to day -5 in the usual sense, but for post-max, there are two different conventions, "u" and "p", both apparently meaning +number of days since maximum light.

**Comment by guillochon** [comment]
This issue was moved to astrocatalogs/supernovae#6
