### ISSUE TITLE
Photometry and Spectra Icons

### ISSUE THREAD

**Issue by jparrent** [astrocatalogs/astrocats#3]
It dawned on me today that the photometry and spectra icons over at sne.space take the user to the same spot. I understand the displays are under construction, but the icons could be merged unless keeping them separate would be better in the long run.

**Comment by guillochon** [comment]
So I've added links from the event names as well, basically any event-related link leads to the event-specific page (name, references, phot., spec.). The icons are separate mostly so we can show the counts separately, I tinkered with combining them and it didn't look good in my opinion.
