### ISSUE TITLE
[SuSpect SN types] Check with SNID

### ISSUE THREAD

**Issue by jparrent** [astrocatalogs/astrocats#39]
Below is a running list of objects with classifications and/or epochs to double check with SNID. 
- [x] 92ac -- Date of maximum appears to be off by ~20 days. This would place peak brightness at May 9 1992 instead of May 29.

**Comment by jparrent** [comment]
@guillochon The date of maximum light for this one can be flagged as erroneous. I see I can do this at sne.space, but we can discuss it later this week.

**Comment by guillochon** [comment]
This issue was moved to astrocatalogs/supernovae#2
