### ISSUE TITLE
supernovae from the future

### ISSUE THREAD

**Issue by saurabhwjha** [astrocatalogs/astrocats#47]
Sorting by discovery date (most recent first), shows a few SN with incorrect discovery dates in the future:
SN 2010kb, SN 2010ka, SN 2010jz, SN 2010jy, SN 2010jx, SN 25747NSV

**Comment by guillochon** [comment]
Verified this issue and attempting to track it down, thanks for bringing it to our attention.

**Comment by guillochon** [comment]
This is now fixed, thanks again!
