### ISSUE TITLE
[LSQ12dlf] duplicate photometry points

### ISSUE THREAD

**Issue by fedhere** [astrocatalogs/astrocats#50]
The V and r photometry seem to be the same datapoints at an offset. In fact there seem to be 2 copies of the V band data, and of many other bands B, I...  and the r data looks like it is a copy of the V data at an offset.

**Comment by fedhere** [comment]
also this is a SLSN, not a Ic i think

**Comment by jparrent** [comment]
Nice finds! I'm working on fixing the typing for this one. @guillochon may have better insights about the duplicate photometry points.

**Comment by fedhere** [comment]
i just downloaded a bunch of stripped lcvs, i may have more findings! one
suggestion: it would be nice to be able to isolate a photometric band, it
should be possible w bokeh (with the 'tap' tool) although i did not find
any examples of multiple points selection w tap

f

On Sat, Jul 9, 2016 at 9:05 PM, J. Parrent notifications@github.com wrote:

> Nice finds! I'm working on fixing the typing for this one. @guillochon
> https://github.com/guillochon may have better insights about the
> duplicate photometry points.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/astrocatalogs/astrocats/issues/50#issuecomment-231564600,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABnkhsMEYMUgm7bnill4RKKHqEsrUF8pks5qUEVYgaJpZM4JIuxQ
> .

## 

 /|/\
   |\*  Please consider the environment before printing this e-mail

**Comment by guillochon** [comment]
This issue was moved to astrocatalogs/supernovae#10

**Comment by guillochon** [comment]
@fedhere I'm moving all these issues to the supernova issue page specifically; the link on the main page wasn't updated to point to the new issue tracker. All three issues are now living here: https://github.com/astrocatalogs/supernovae/issues
