### ISSUE TITLE
[SN2013df] missing data and reference

### ISSUE THREAD

**Issue by fedhere** [astrocatalogs/astrocats#53]
there is VanDyk+ 2013  reference (3)  but i do not see the NIR photometry, or any optical photometry associated to reference (3) a significant amount of photometry available for this object. And there is a missing reference to Morales-Garoffolo+ 2014 (some of their data is also in Brown 15, but not all). I will try and upload it.

**Comment by lzkelley** [comment]
Migrated to `supernovae` catalog
