### ISSUE TITLE
Can't use --depth command anymore?

### ISSUE THREAD

**Issue by guillochon** [astrocatalogs/astrocats#64]
The --depth arg was used to restrict the depth of the repositories checked out, but it appears that it can no longer be passed, unless the syntax has changed to something weird. I tried several combinations and none worked:

```
python -m astrocats --depth 1 supernovae import

python -m astrocats supernovae import --depth 1
```

The --depth arg is needed to get the Travis build working, otherwise we run into Travis' disk quota.

**Comment by lzkelley** [comment]
I think this is just not being parsed and passed by the argparse.  Should be an easy fix I can take care of this afternoon.

**Comment by lzkelley** [comment]
No, actually, it's just that the argument was `--git-depth` instead of `--depth`.
**BUT** I just changed it to `--clone-depth` (and variable `clone_depth`) for clarity.
