### ISSUE TITLE
Photometry: 'u_time': MJD is being added as default even to 'host' entries without time value

### ISSUE THREAD

**Issue by lzkelley** [astrocatalogs/astrocats#66]
The default `'u_time': 'MJD'` should probably only be set if the `Photometry` has a `'time'` value.

**Comment by guillochon** [comment]
Good catch, this oughta fix it: https://github.com/astrocatalogs/astrocats/commit/37c0378e0e7ac3a9d473f8870fda6d8f107593f2

**Comment by lzkelley** [comment]
Yup, that fixed it!  Thanks
