### ISSUE TITLE
Get 'update' mode working again

### ISSUE THREAD

**Issue by lzkelley** [astrocatalogs/astrocats#71]
- [x] Only `update=True` tasks are being run now.
- [x] Update mode is working.

**Comment by guillochon** [comment]
At the moment, the primary issue in getting this working is how the boneyard is handled. Currently we just do a boneyard check in the `cleanup` task but nowhere else. When we load a file the functions that delete the file from disk are not aware of when a file originates from the boneyard.

**Comment by guillochon** [comment]
Update mode works, closing.
