### ISSUE TITLE
[Catalog Table] Sorting by luminosity distance

### ISSUE THREAD

**Issue by jparrent** [astrocatalogs/astrocats#9]
Just noticed this. When I order SN Ia ('Ia') in the table at sne.space by luminosity distance (nearest events at the top, so increasing distance downward), the events that do not have a distance are returned first. Is there a way to have the events with NULL or empty entries go somewhere else when sorted? I imagine it would have to work both ways too, either increasing or decreasing luminosity distance. For example, page 12 is when the first nearest distance measurement shows up (SN 1604A). The page flipping is fast enough that it's still readily usable, but just a heads up.

**Comment by guillochon** [comment]
This was something I was trying to accomplish for a long time, but I was finding that the sort was horribly slow when trying to find blanks. I actually just figured out the way to get this to work quickly ([lonnng exchange on the DataTables forums about it](http://datatables.net/forums/discussion/comment/90286#Comment_90286)). Now, the table does sort the numeric columns with the blanks appearing at the bottom, and fast!
