### ISSUE TITLE
api.astrocats.space certificate expired 

### ISSUE THREAD

**Issue by CheerfulUser** [astrocatalogs/astrocats#94]
It looks like the web certificate for astrocats.space has expired preventing the api from working.
![Screen Shot 2022-06-10 at 10 02 15 AM](https://user-images.githubusercontent.com/25831737/172952780-f32c1571-912c-42d9-8a5d-a9b385979ab5.png)

**Comment by guillochon** [comment]
Sorry about that! I've renewed the certs. You may need to clear your cache but it should be working now.

**Comment by CheerfulUser** [comment]
Awesome! Thanks for fixing that so quickly!
